import * as Crypto from "effect/Crypto";
import { Atom } from "effect/unstable/reactivity";

import { createAtomCommandScheduler, createEnvironmentCommand } from "./runtime.ts";
import {
  type AddThreadMemberInput,
  type ArchiveThreadInput,
  type CreateThreadInput,
  // T3-CUSTOM(expbkt3): durable bootstrap command atoms.
  type RequestThreadBootstrapInput,
  type RetryThreadBootstrapInput,
  type StopThreadBootstrapInput,
  type ContinueThreadBootstrapInput,
  type DeleteThreadInput,
  type InterruptThreadTurnInput,
  type RemoveThreadMemberInput,
  type RespondToThreadApprovalInput,
  type RespondToThreadUserInputInput,
  type RequestThreadCatchupSummaryInput,
  type RevertThreadCheckpointInput,
  type RestartThreadSessionInput,
  type SetThreadInteractionModeInput,
  type SetThreadRuntimeModeInput,
  type SettleThreadInput,
  type SnoozeThreadInput,
  type StartThreadTurnInput,
  type StopThreadSessionInput,
  type StopThreadExecutionInput,
  type TransferThreadOwnershipInput,
  type UnarchiveThreadInput,
  type UnsettleThreadInput,
  type UnsnoozeThreadInput,
  type UpdateThreadMetadataInput,
  addThreadMember,
  archiveThread,
  createThread,
  requestThreadBootstrap,
  retryThreadBootstrap,
  stopThreadBootstrap,
  continueThreadBootstrap,
  deleteThread,
  interruptThreadTurn,
  removeThreadMember,
  respondToThreadApproval,
  respondToThreadUserInput,
  requestThreadCatchupSummary,
  revertThreadCheckpoint,
  restartThreadSession,
  setThreadInteractionMode,
  setThreadRuntimeMode,
  settleThread,
  snoozeThread,
  startThreadTurn,
  stopThreadSession,
  stopThreadExecution,
  transferThreadOwnership,
  unarchiveThread,
  unsettleThread,
  unsnoozeThread,
  updateThreadMetadata,
} from "../operations/commands.ts";
import type { EnvironmentRegistry } from "../connection/registry.ts";

export { OrchestrationCommandAcknowledgementTimeoutError } from "../operations/commands.ts";

export type {
  AddThreadMemberInput,
  ArchiveThreadInput,
  CreateThreadInput,
  RequestThreadBootstrapInput,
  RetryThreadBootstrapInput,
  StopThreadBootstrapInput,
  ContinueThreadBootstrapInput,
  DeleteThreadInput,
  InterruptThreadTurnInput,
  RemoveThreadMemberInput,
  RespondToThreadApprovalInput,
  RequestThreadCatchupSummaryInput,
  RespondToThreadUserInputInput,
  RevertThreadCheckpointInput,
  RestartThreadSessionInput,
  SetThreadInteractionModeInput,
  SetThreadRuntimeModeInput,
  SettleThreadInput,
  SnoozeThreadInput,
  StartThreadTurnInput,
  StopThreadSessionInput,
  StopThreadExecutionInput,
  TransferThreadOwnershipInput,
  UnarchiveThreadInput,
  UnsettleThreadInput,
  UnsnoozeThreadInput,
  UpdateThreadMetadataInput,
} from "../operations/commands.ts";

export function createThreadEnvironmentAtoms<R, E>(
  runtime: Atom.AtomRuntime<EnvironmentRegistry | Crypto.Crypto | R, E>,
) {
  const scheduler = createAtomCommandScheduler();
  const concurrency = {
    mode: "serial" as const,
    key: ({ environmentId, input }: { environmentId: string; input: { threadId: string } }) =>
      JSON.stringify([environmentId, input.threadId]),
  };
  return {
    create: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:create",
      execute: (input: CreateThreadInput) => createThread(input),
      scheduler,
      concurrency,
    }),
    // T3-CUSTOM(expbkt3): expose durable bootstrap controls to every client runtime.
    requestBootstrap: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:bootstrap-request",
      execute: (input: RequestThreadBootstrapInput) => requestThreadBootstrap(input),
      scheduler,
      concurrency,
    }),
    retryBootstrap: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:bootstrap-retry",
      execute: (input: RetryThreadBootstrapInput) => retryThreadBootstrap(input),
      scheduler,
      concurrency,
    }),
    stopBootstrap: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:bootstrap-stop",
      execute: (input: StopThreadBootstrapInput) => stopThreadBootstrap(input),
      scheduler,
      concurrency,
    }),
    continueBootstrap: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:bootstrap-continue",
      execute: (input: ContinueThreadBootstrapInput) => continueThreadBootstrap(input),
      scheduler,
      concurrency,
    }),
    delete: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:delete",
      execute: (input: DeleteThreadInput) => deleteThread(input),
      scheduler,
      concurrency,
    }),
    archive: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:archive",
      execute: (input: ArchiveThreadInput) => archiveThread(input),
      scheduler,
      concurrency,
    }),
    unarchive: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unarchive",
      execute: (input: UnarchiveThreadInput) => unarchiveThread(input),
      scheduler,
      concurrency,
    }),
    settle: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:settle",
      execute: (input: SettleThreadInput) => settleThread(input),
      scheduler,
      concurrency,
    }),
    unsettle: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unsettle",
      execute: (input: UnsettleThreadInput) => unsettleThread(input),
      scheduler,
      concurrency,
    }),
    snooze: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:snooze",
      execute: (input: SnoozeThreadInput) => snoozeThread(input),
      scheduler,
      concurrency,
    }),
    unsnooze: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unsnooze",
      execute: (input: UnsnoozeThreadInput) => unsnoozeThread(input),
      scheduler,
      concurrency,
    }),
    updateMetadata: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:update-metadata",
      execute: (input: UpdateThreadMetadataInput) => updateThreadMetadata(input),
      scheduler,
      concurrency,
    }),
    setRuntimeMode: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:set-runtime-mode",
      execute: (input: SetThreadRuntimeModeInput) => setThreadRuntimeMode(input),
      scheduler,
      concurrency,
    }),
    setInteractionMode: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:set-interaction-mode",
      execute: (input: SetThreadInteractionModeInput) => setThreadInteractionMode(input),
      scheduler,
      concurrency,
    }),
    startTurn: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:start-turn",
      execute: (input: StartThreadTurnInput) => startThreadTurn(input),
      scheduler,
      concurrency,
    }),
    interruptTurn: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:interrupt-turn",
      execute: (input: InterruptThreadTurnInput) => interruptThreadTurn(input),
      scheduler,
      concurrency,
    }),
    stopExecution: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:stop-execution",
      execute: (input: StopThreadExecutionInput) => stopThreadExecution(input),
      scheduler,
      concurrency,
    }),
    respondToApproval: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:respond-to-approval",
      execute: (input: RespondToThreadApprovalInput) => respondToThreadApproval(input),
      scheduler,
      concurrency,
    }),
    respondToUserInput: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:respond-to-user-input",
      execute: (input: RespondToThreadUserInputInput) => respondToThreadUserInput(input),
      scheduler,
      concurrency,
    }),
    revertCheckpoint: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:revert-checkpoint",
      execute: (input: RevertThreadCheckpointInput) => revertThreadCheckpoint(input),
      scheduler,
      concurrency,
    }),
    requestCatchupSummary: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:request-catchup-summary",
      execute: (input: RequestThreadCatchupSummaryInput) => requestThreadCatchupSummary(input),
      scheduler,
      concurrency,
    }),
    stopSession: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:stop-session",
      execute: (input: StopThreadSessionInput) => stopThreadSession(input),
      scheduler,
      concurrency,
    }),
    restartSession: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:restart-session",
      execute: (input: RestartThreadSessionInput) => restartThreadSession(input),
      scheduler,
      concurrency,
    }),
    addMember: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:add-member",
      execute: (input: AddThreadMemberInput) => addThreadMember(input),
      scheduler,
      concurrency,
    }),
    removeMember: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:remove-member",
      execute: (input: RemoveThreadMemberInput) => removeThreadMember(input),
      scheduler,
      concurrency,
    }),
    transferOwnership: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:transfer-ownership",
      execute: (input: TransferThreadOwnershipInput) => transferThreadOwnership(input),
      scheduler,
      concurrency,
    }),
  };
}
